# Generated by Django 6.0.3 on 2026-03-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('flight_id', models.IntegerField()),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.IntegerField()),
                ('passenger_gender', models.CharField(max_length=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
